# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ByoRatingViewExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ByoRatingViewExample
  pod 'ByoRatingView', path: '../'
  
  pod 'ToastQueue', :git => 'https://github.com/byoth/ToastQueue.git'
end
